const personajes = [
	{
		nombre: 'Cassiopeia',
		articulos: '3 items',
		precio: 'uno',
		vida: '500 a 1620',
		rango: true,
        habilidad: 'Mago',
        origen: 'Noxus y Shurima',
        clase: 'Invocador',
        sinergias: 'Renekton Samira Taliyah Kled Swain'
	},
	{
		nombre: 'Chogath',
		articulos: '3 items',
		precio: 'uno',
		vida: '700 a 2268',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Vacio',
        clase: 'Maton',
        sinergias: 'Kassadin Malzahar'
	},
	{
		nombre: 'Irelia',
		articulos: '3 items',
		vida: '700 a 2268',
		precio: 'uno',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Jonia',
        clase: 'Retador',
        sinergias: 'Jhin Sett Warwick Zed'
	},
	{
		nombre: 'Jhin',
		articulos: '3 items',
		vida: '504 a 1633',
		precio: 'uno',
		rango: true,
        habilidad: 'Pistolero',
        origen: 'Jonia',
        clase: 'Doble Tirador',
        sinergias: 'Ashe Irelia Zed'
	},
	{
		nombre: 'Kayle',
		articulos: '3 items',
		vida: '500 a 1620',
		precio: 'uno',
		rango: true,
        habilidad: 'Fusilador',
        origen: 'Demacia',
        clase: 'Fulminador',
        sinergias: 'Galio Kled Poppy Zed'
	},
	{
		nombre: 'Malzahar',
		articulos: '3 items',
		vida: '500 a 1620',
		precio: 'uno',
		rango: true,
        habilidad: 'Mago',
        origen: 'Vacio',
        clase: 'Mago',
        sinergias: 'Chogath Kassadin Orianna'
	},
	{
		nombre: 'Maokai',
		articulos: '3 items',
		vida: '700 a 2268',
		precio: 'uno',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Islas de las sombras',
        clase: 'Bastion',
        sinergias: 'Poppy Kassadin Viego'
	},
	{
		nombre: 'Orianna',
		articulos: '3 items',
		vida: '500 a 1620',
		precio: 'uno',
		rango: true,
        habilidad: 'Mago',
        origen: 'Piltover',
        clase: 'Mago',
        sinergias: 'Malzahar Jinx Vi Swain'
	},
	{
		nombre: 'Poppy',
		articulos: '3 items',
		vida: '600 a 1944',
		precio: 'uno',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Demacia y Yordle',
        clase: 'Bastion',
        sinergias: 'Tristana Kled Kayle Teemo Galio Maokai Kassadin'
	},
	{
		nombre: 'Renekton',
		articulos: '3 items',
		vida: '600 a 1944',
		precio: 'uno',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Shurima',
        clase: 'Maton',
        sinergias: 'Cassiopeia Chogath Taliyah Vi'
	},
	{
		nombre: 'Samira',
		articulos: '3 items',
		vida: '500 a 1620',
		precio: 'uno',
		rango: true,
        habilidad: 'Pistolero',
        origen: 'Noxus',
        clase: 'Retador',
        sinergias: 'Cassiopeia Irelia Kled Swain Warwick'
	},
	{
		nombre: 'Tristana',
		articulos: '3 items',
		vida: '400 a 1296',
		precio: 'uno',
		rango: true,
        habilidad: 'Pistolero',
        origen: 'Yordle',
        clase: 'Artillero',
        sinergias: 'Poppy Teemo Kled Jinx'
	},
	{
		nombre: 'Viego',
		articulos: '3 items',
		vida: '600 a 1944',
		precio: 'uno',
		rango: false,
        habilidad: 'Fusilador',
        origen: 'Islas de las sombras',
        clase: 'Asesino',
        sinergias: 'Maokai Zed'
	},
	{
		nombre: 'Ashe',
		articulos: '3 items',
        vida: '600 a 1944',
		precio: 'dos',
		rango: true,
        habilidad: 'Pistolero',
        origen: 'Freljord',
        clase: 'Doble tirador',
        sinergias: 'Jhin'
	},
	{
		nombre: 'Galio',
		articulos: '3 items',
        vida: '800 a 2592',
		precio: 'dos',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Demacia',
        clase: 'Invocador',
        sinergias: 'Kayle Poppy Cassiopeia Soraka'
	},
	{
		nombre: 'Jinx',
		articulos: '3 items',
        vida: '600 a 1944',
		precio: 'dos',
		rango: true,
        habilidad: 'Pistolero',
        origen: 'Zaun',
        clase: 'Artillero',
        sinergias: 'Warwick Tristana'
	},
	{
		nombre: 'Kassadin',
		articulos: '3 items',
        vida: '800 a 2592',
		precio: 'dos',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Vacio',
        clase: 'Bastion',
        sinergias: 'Chogath Malzahar Maokai Poppy'
	},
	{
		nombre: 'Kled',
		articulos: '3 items',
        vida: '550 a 1782',
		precio: 'dos',
		rango: false,
        habilidad: 'Fusilador',
        origen: 'Noxus y Yordle',
        clase: 'Fulminador',
        sinergias: 'Cassiopeia Samila Swain Poppy Teemo Tristana Kayle Zed'
	},
	{
		nombre: 'Sett',
		articulos: '3 items',
        vida: '800 a 2592',
		precio: 'dos',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Jonia',
        clase: 'Coloso',
        sinergias: 'Irelia Jhin Zed Warwick'
	},
    {
		nombre: 'Soraka',
		articulos: '3 items',
        vida: '700 a 2268',
		precio: 'dos',
		rango: true,
        habilidad: 'Cura',
        origen: 'Targon',
        clase: 'Invocador',
        sinergias: 'Cassiopeia Galio'
	},
    {
		nombre: 'Swain',
		articulos: '3 items',
        vida: '800 a 2592',
		precio: 'dos',
		rango: true,
        habilidad: 'Mago',
        origen: 'Noxus',
        clase: 'Mago y Estratega',
        sinergias: 'Cassiopeia Kled Samira Teemo Malzahar Orianna'
	},
    {
		nombre: 'Taliyah',
		articulos: '3 items',
        vida: '550 a 1782',
		precio: 'dos',
		rango: true,
        habilidad: 'Mago',
        origen: 'Shurima',
        clase: 'Doble lanzador',
        sinergias: 'Cassiopeia Renekton Teemo'
	},
    {
		nombre: 'Teemo',
		articulos: '3 items',
        vida: '500 a 1620',
		precio: 'dos',
		rango: true,
        habilidad: 'Mago',
        origen: 'Yordle',
        clase: 'Doble Lanzador y Estratega',
        sinergias: 'Kled Poppy Tristana Swain Taliyah'
	},
    {
		nombre: 'Vi',
		articulos: '3 items',
        vida: '50',
		precio: 'dos',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Piltover',
        clase: 'Maton',
        sinergias: 'Orianna Chogath Renekton'
	},
    {
		nombre: 'Warwick',
		articulos: '3 items',
        vida: '800 a 2592',
		precio: 'dos',
		rango: false,
        habilidad: 'Tanque',
        origen: 'Zaun',
        clase: 'Retador y Coloso',
        sinergias: 'Jinx Sett Irelia Samira'
	},
    {
		nombre: 'Zed',
		articulos: '3 items',
        vida: '600 a 1944',
		precio: 'dos',
		rango: false,
        habilidad: 'Fusilador',
        origen: 'Jonia',
        clase: 'Fulminador y Asesino',
        sinergias: 'Irelia Jhin Sett Viego Kayle Kled'
	},
]